### ISSUE TITLE
Problem statement submit

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#1]
Hi Dr. Smith,

Please check the submission for the problem statement. [Here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) is the link.

Regards,
Cynthia

**Comment by smiths** [comment]
Feedback:

- put a space before (RC)
- add a mention of Dr. Yang and Mingsai to  your problem statement

Looks good.  I'm looking forward to seeing this project come together.

Your project is approved.  :smile:
