### ISSUE TITLE
Section 3.1 (Diagram)

### ISSUE THREAD

**Issue by cer-hunter** [CynthiaLiu0805/BridgeCorrosion#12]
Are the dataset inputs needed in the System Context if they aren't being directly input by the user? Or maybe the Dataset should be another circle node as input to the program in the diagram.
[SRS](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/SRS/SRS.pdf)

**Comment by CynthiaLiu0805** [comment]
I put it in separate circle node in effdfca
