### ISSUE TITLE
VnVPlan submit

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#15]
Hi Dr. Smith,

[Here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/VnVPlan/VnVPlan.pdf) is my VnVPlan, I would be happy to hear any feedback or comments.

Thanks,
Cynthia

**Comment by smiths** [comment]
[Cynthia_VnVPlan.pdf](https://github.com/CynthiaLiu0805/BridgeCorrosion/files/14566719/Cynthia_VnVPlan.pdf)
