### ISSUE TITLE
VnVPlan Domain Expert

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#16]
Hi Phil,

[Here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/VnVPlan/VnVPlan.pdf) is my VnVPlan, I would be happy to hear any feedback or comments.

Thanks,
Cynthia

**Comment by omltcat** [comment]
Hi Cynthia,

I have created my feedback issues: #18 #19 #20 #21 #22.

Some of these are more of questions than issues. Maybe I am not understanding some aspects very clearly. Please take a look.

Thanks,
Phil
