### ISSUE TITLE
Input test with NONE output

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#18]
Section 4.1.1

If I understand it correctly, the idea of Section 4 is to test the input and output of the ENTIRE system. So for coordinate inputs, if it they are not valid, then naturally the program should output an error like you said. But if the inputs ARE valid, then the program should just run normally and eventually output an valid answer (in terms of chloride exposure), instead of NONE. 

This can probably be combined with 4.1.3 into one.

**Comment by CynthiaLiu0805** [comment]
Yes, you are right, I was trying to mean there is no error message. Resolved in ea69294.
