### ISSUE TITLE
Intermediate Tests Steps

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#19]
Section 4.1.2

Same idea as in #18, Section 4 is at a system level. Hypothetically, when we write this section, we should not have thought about how the program works under the hood (which is likely not the case for most of us but let's just pretend). 

So the steps in 4.1.2 are probably more suited to be in Section 5 Unit Test.

**Comment by CynthiaLiu0805** [comment]
I agree with you. I was thinking section 4.1.2 was too detailed for the system level as well. Will come back to it when writing unit testing.

**Comment by CynthiaLiu0805** [comment]
Fix in [60a803b](https://github.com/CynthiaLiu0805/BridgeCorrosion/commit/60a803bcb11c410a43de5db6295328ee1540a05e) by implementing them as unit test.
