### ISSUE TITLE
SRS submit

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#2]
Hi,

Please check the submission for the SRS. [Here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/SRS/SRS.pdf) is the link.

Regards,
Cynthia

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[CynthiaLiu_SRS.pdf](https://github.com/CynthiaLiu0805/BridgeCorrosion/files/14389827/CynthiaLiu_SRS.pdf)
