### ISSUE TITLE
Portability and Scalability Tests

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#21]
This is more of a question than an issue.

From SRS:
> NFR4: Portability: This software should be able to run on recent versions of Google Chrome, Firefox, MS Edge and Safari. The operating system include Windows 7+ and Mac OS X 10.7+.

After reading this I thought it is going to be some web app.

But then in VnV:
> The first part of the software, generating the database through climate and traffic model, will be done in MATLAB. The second part of finding the data for the input location, will be done in R. 

So I suppose idea is, there is going to be some MATLAB/R backend, and user would access it via a browser.

My question is: 
Does the user run the backend on their own computer, and just use the browser as an UI, or is there a centralized server hosting the backend, and the user would visit the website? I understand this is more of a design choice for later, but it could have different implications on the NFR tests.

If the user need to run the backend themselves, then the Portability test should probably focus on if their computers can actually run the R program, how easy it is to set everything up. The browser part is likely least of the concerns.  

If there is going to be a hosted server as backend, then Scalability should probably include a multiple users stress test.

**Comment by CynthiaLiu0805** [comment]
MATLAB will only be used to generate the database from the traffic and climate model so the users will not actually get in touch with it. The database is likely to be a csv file and the main purpose of R is to find the data by coordinate in the csv file. There will not be a hosted server as backend so I think you are correct about running R on the users' computer, I will add more about installing R in the document.

**Comment by CynthiaLiu0805** [comment]
After everything I moved the whole implementation to python and the website will be run on localhost. I add lots of information in Readme.md for portability in ce5e249e4928773d42351bae71c083f5d1c1df68. Since every user will run it on the individual computer, it does not need a multiple users stress test.
