### ISSUE TITLE
MG+MIS submit

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#33]
Hi Dr. Smith,

[Here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/Design/SoftArchitecture/MG.pdf) is my MG and [here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)  is my MIS, I would be happy to hear any feedback or comments.

Thanks,
Cynthia

**Comment by smiths** [comment]
[CynthiaMG.pdf - PDF Expert.pdf](https://github.com/CynthiaLiu0805/BridgeCorrosion/files/14846157/CynthiaMG.pdf.-.PDF.Expert.pdf)

[CynthiaMIS.pdf - PDF Expert.pdf](https://github.com/CynthiaLiu0805/BridgeCorrosion/files/14846158/CynthiaMIS.pdf.-.PDF.Expert.pdf)
