### ISSUE TITLE
MG+MIS Domain Expert

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#34]
Hi Phil,

[Here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/Design/SoftArchitecture/MG.pdf) is my MG and [here](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)  is my MIS, I would be happy to hear any feedback or comments.

Thanks,
Cynthia

**Comment by omltcat** [comment]
Hi Cynthia,

Good work on MG and MIS. I like the idea of having the appendix for quick reference. Reading yours also made me realized a few problems of my own documents, thanks. 

The issues are created as: #42 #43 #44 #45 #46 #47 #48 #49 #50.

Phil
