### ISSUE TITLE
MG Review - Table2

### ISSUE THREAD

**Issue by AtiyehSayadi** [CynthiaLiu0805/BridgeCorrosion#40]
It is better to display a list of requirements before the table so that the relationship between modules and requirements becomes clearer. Additionally, it seems you have only used functional requirements, whereas non-functional requirements would also be beneficial to mention.

**Comment by CynthiaLiu0805** [comment]
I think so too but was not sure where to add it. I put an appendix section at the end with that information. Fix in 1b0f41f.
