### ISSUE TITLE
MG: AC2 ambiguous wording

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#42]
> AC2: The dataset input from climate and traffic model need to be updated manually every year.

I can understand this sentence in two ways:
1. The "change" you have in mind is literally the UPDATE of the dataset every year. 
2. You want to change the software so that it does not to be updated manually.

If 1 is the case, I don't think it is quite inline with the spirit of AC, which is changing how the software works under the hood. It is more of a necessary maintenance you have designed.

**Comment by CynthiaLiu0805** [comment]
Yes, 1 is the case. I think you are correct, I have removed it and modified related content accordingly in f96433b.
