### ISSUE TITLE
MG: M2 and M6 Type of Module "Function"?

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#43]
Do you mean "Library", or are they literally just ONE function?

Also, is there a reason why you would separate M2 from M3? It sounds like M2 is just the first step of M3.

**Comment by CynthiaLiu0805** [comment]
That is a good point, when I started writing implementation I realized M2 is actually just a few functions converting types. Will reorganize these parts later.

**Comment by CynthiaLiu0805** [comment]
Fixed in 1f2ad8efdb1b2fc2f2ec788257fa8a66a5ec3a06 by putting them in one module
