### ISSUE TITLE
MG: M9 Implemented By and Type

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#44]
> Implemented By: Python
> Type of Module: Plotly Library

I think the way to say it is:

> Implemented By: Plotly 
> Type of Module: Library

"Implemented By" indicates who is responsible for this functionality.

**Comment by CynthiaLiu0805** [comment]
Yes, I agree with you and this has been fixed in a previous commit ec81ace.
