### ISSUE TITLE
MIS: Inputs to Control Module

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#46]
> long, lat := long: R, lat: R # input coordinate get from Input Parameter Module.

So if I understand this correctly, main calls Input Verification Module (from UI?), which calls Input Parameter Module, which returns lat, long.

That is not "input" to main. 

Input to the main module is probably more like arguments you give when starting the whole program.

**Comment by CynthiaLiu0805** [comment]
I get it, your explanation is so clear, thanks for that. Fixed in f483669.
