### ISSUE TITLE
MIS: Output of draw

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#49]
Is graph and file a output (something returned by the function) or just a transition (update the environment variable)

**Comment by CynthiaLiu0805** [comment]
The graph is a transition as in 10.4.4:
draw($long, lat, result$): transition: display the graphs using the result from Data Searching Module.

The file is an output as in 11.4.4:
calculate($AADT, AADTT, t1, h_{total}, t2$): output: out :=  file = ... \# the result is saved to a csv file storing the calculation result, which is the prediction of chloride exposure rate. The file has a row label as coordinate and a column label as year.
