### ISSUE TITLE
Issue #5 VnV Plan: Section 4.1.2. 

### ISSUE THREAD

**Issue by FasilCheema** [CynthiaLiu0805/BridgeCorrosion#56]
Section 4.1.2 I believe this should be a unit test as you state. This is a test for this specific module’s calculation and a unit test seems more well suited.

**Comment by CynthiaLiu0805** [comment]
Yes I move them to unit test section in [60a803b](https://github.com/CynthiaLiu0805/BridgeCorrosion/commit/60a803bcb11c410a43de5db6295328ee1540a05e).
