### ISSUE TITLE
Issue #6 VnV Plan: Minor Issues

### ISSUE THREAD

**Issue by FasilCheema** [CynthiaLiu0805/BridgeCorrosion#57]
Minor Issues

1. table 2, section 4.1.1. 1st error message calculate is mispelled
2. table 2, section 4.1.1. 5th error message calculate is mispelled
3. table 2, section 4.1.1. 6th error message calculate is mispelled
4. section 4.1.1. Test Case Derivation; spencer smith feedback is still enabled
5. section 4.1.2 The sentence at the end of the first paragraph “There are six steps over the calculation process following section 4.4 in SRS as follow.” should be replaced with:  “ There are six steps over the calculation process following section 4.4 in SRS as follows:”
6. Delete all spencer smith comments (can be done simply by disabling comments in common.tex)

**Comment by CynthiaLiu0805** [comment]
Thank you for the detailed feedback, fixed in [60a803b](https://github.com/CynthiaLiu0805/BridgeCorrosion/commit/60a803bcb11c410a43de5db6295328ee1540a05e)
