### ISSUE TITLE
MG + MIS - Input Module Secret

### ISSUE THREAD

**Issue by rnorouziani** [CynthiaLiu0805/BridgeCorrosion#58]
The secret of the Input module could be the format and structure of the input data, but what you mentioned is the kind of valid and invalid input coordinate data, which I assume could be considered a secondary secret.

**Comment by CynthiaLiu0805** [comment]
The input data is pretty straightforward as they are simply string of coordinate, the valid and invalid input data is included because I also do the input verification in the input module.
