### ISSUE TITLE
Untracable design decision in System Context

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#6]
In 3.1 System Context - Bridge Corrosion Responsibilities:
- Build a database storing the chloride exposure data for **_every 25 km_** over time.

Where is the 25 km coming from? It is not mentioned anywhere else in the document. Is it because of the source dataset or is it a requirement made by someone (the research team? MTO?), or system limitations?. Please provide some justification so that it does not sound like an arbitrary design decision.

**Comment by CynthiaLiu0805** [comment]
Add scope decision to explain the 25km is from the limit of the climate data model.
