### ISSUE TITLE
Inputs other than the coordinates

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#7]
In 4.2.1 Types, only the coordinate inputs are mentioned.
However 4.2.7 Input Data Constraints lists an entirely different set of input.

I assume the idea of this software is to take the datasets mentioned in 4.1.3 and use the models listed in 4.2 to build a chloride exposure map over time. Then the user would input coordinate to query the chloride exposure. Am I understanding it correctly?

If so this should be conveyed more clearly: each model uses which value coming from which dataset.

Also, is the dataset part of the software (maintained by the developer) or must be provided by the users before querying the coordinates? I assume it's the first case.

**Comment by CynthiaLiu0805** [comment]
You are right, the dataset input is maintained by the developer. I added the dataset input in the system context and types correspondingly to talk about this in 10a2cf4.
