### ISSUE TITLE
The time aspect

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#8]
The phrase "over time" is mentioned in the document multiple times

e.g. "R2: The output need to be a series of data showing the trend of chloride exposure over time at the input location (By IM2)."

But this can be understood in multiple ways. Is it only for past times where data exists, or does the software also provide future prediction? What about the time range and granularity (which are potentially user inputs?).

**Comment by CynthiaLiu0805** [comment]
The software provides output for both past and future, the time range and granularity are the input from the climate/traffic model dataset(which is mentioned in another issue and will be fixed there). The phrase for over time is fixed in b555dd6
