### ISSUE TITLE
Confliciting Goal and Requirement regarding location

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#9]
GS2: Allow user to input coordinate and return the prediction for the **_nearest bridge_**.

R2: The output need to be a series of data showing the trend of chloride exposure over
time **_at the input location_** (By IM2).

So is the result for the input coordinate or the bridge closest to such coordinate?

**Comment by CynthiaLiu0805** [comment]
The result would be the data for input coordinate, but if the input coordinate does not have a bridge on it, it would return the value of the nearest bridge. This is fixed in 96fdada.
